name: Automatic changelog procedures

on:
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run update readme script
        run: python update_readme_on_push.py

      - name: Run tag dumping script
        run: python dump_tags_on_push.py
